### PR TITLE
testing(sample): fix broken tests

### LINKED ISSUE #104: samples.snippets.quickstart_searchallresources_test: test_search_all_resources failed
Note: #75 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: b112f29a34b30e15b467996755da3c4123fa19f3
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/e99201d7-bc2e-4f6a-88e1-475e11b4b51e), [Sponge](http://sponge2/e99201d7-bc2e-4f6a-88e1-475e11b4b51e)
status: failed
<details><summary>Test output</summary><br><pre>asset_dataset = 'dataset_7df1a602b1ea49129966874e6e1e78d8'
capsys = <_pytest.capture.CaptureFixture object at 0x7fa54682bdc0>

    @pytest.mark.flaky(max_runs=3, min_passes=1)
    def test_search_all_resources(asset_dataset, capsys):
        scope = "projects/{}".format(PROJECT)
        query = "name:{}".format(DATASET)
    
        # Dataset creation takes some time to propagate, so the dataset is not
        # immediately searchable. Need some time before the snippet will pass.
        @backoff.on_exception(backoff.expo, (AssertionError), max_time=120)
        def eventually_consistent_test():
            quickstart_searchallresources.search_all_resources(scope, query=query)
            out, _ = capsys.readouterr()
    
            assert DATASET in out
    
>       eventually_consistent_test()

quickstart_searchallresources_test.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.nox/py-3-8/lib/python3.8/site-packages/backoff/_sync.py:94: in retry
    ret = target(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @backoff.on_exception(backoff.expo, (AssertionError), max_time=120)
    def eventually_consistent_test():
        quickstart_searchallresources.search_all_resources(scope, query=query)
        out, _ = capsys.readouterr()
    
>       assert DATASET in out
E       AssertionError: assert 'dataset_7df1a602b1ea49129966874e6e1e78d8' in ''

quickstart_searchallresources_test.py:61: AssertionError</pre></details>

### LINKED ISSUE #105: samples.snippets.quickstart_batchgetassetshistory_test: test_batch_get_assets_history failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: b112f29a34b30e15b467996755da3c4123fa19f3
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/0ef736c2-99a6-4f41-836d-649040d36175), [Sponge](http://sponge2/0ef736c2-99a6-4f41-836d-649040d36175)
status: failed
<details><summary>Test output</summary><br><pre>args = (parent: "projects/python-docs-samples-tests"
asset_names: "//storage.googleapis.com/assets-2e67da2f1fed466d8d2352d28c811f2e"
content_type: RESOURCE
read_time_window {
}
,)
kwargs = {'metadata': [('x-goog-request-params', 'parent=projects/python-docs-samples-tests'), ('x-goog-api-client', 'gl-python/3.8.3 grpc/1.33.2 gax/1.23.0 gapic/2.1.0')]}

    @six.wraps(callable_)
    def error_remapped_callable(*args, **kwargs):
        try:
>           return callable_(*args, **kwargs)

.nox/py-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <grpc._channel._UnaryUnaryMultiCallable object at 0x7f2e10ad7fd0>
request = parent: "projects/python-docs-samples-tests"
asset_names: "//storage.googleapis.com/assets-2e67da2f1fed466d8d2352d28c811f2e"
content_type: RESOURCE
read_time_window {
}

timeout = None
metadata = [('x-goog-request-params', 'parent=projects/python-docs-samples-tests'), ('x-goog-api-client', 'gl-python/3.8.3 grpc/1.33.2 gax/1.23.0 gapic/2.1.0')]
credentials = None, wait_for_ready = None, compression = None

    def __call__(self,
                 request,
                 timeout=None,
                 metadata=None,
                 credentials=None,
                 wait_for_ready=None,
                 compression=None):
        state, call, = self._blocking(request, timeout, metadata, credentials,
                                      wait_for_ready, compression)
>       return _end_unary_response_blocking(state, call, False, None)

.nox/py-3-8/lib/python3.8/site-packages/grpc/_channel.py:923: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

state = <grpc._channel._RPCState object at 0x7f2e10adf700>
call = <grpc._cython.cygrpc.SegregatedCall object at 0x7f2e10ad0dc0>
with_call = False, deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
>           raise _InactiveRpcError(state)
E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E           	status = StatusCode.INVALID_ARGUMENT
E           	details = "The following 1 resources don't exist in projects/1012616486416 : //storage.googleapis.com/assets-2e67da2f1fed466d8d2352d28c811f2e"
E           	debug_error_string = "{"created":"@1604055783.582880103","description":"Error received from peer ipv4:74.125.20.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"The following 1 resources don't exist in projects/1012616486416 : //storage.googleapis.com/assets-2e67da2f1fed466d8d2352d28c811f2e","grpc_status":3}"
E           >

.nox/py-3-8/lib/python3.8/site-packages/grpc/_channel.py:826: _InactiveRpcError

The above exception was the direct cause of the following exception:

asset_bucket = 'assets-2e67da2f1fed466d8d2352d28c811f2e'
capsys = <_pytest.capture.CaptureFixture object at 0x7f2e11222af0>

    def test_batch_get_assets_history(asset_bucket, capsys):
        bucket_asset_name = "//storage.googleapis.com/{}".format(BUCKET)
        asset_names = [
            bucket_asset_name,
        ]
    
        @backoff.on_exception(backoff.expo, (AssertionError, InvalidArgument), max_time=30)
        def eventually_consistent_test():
            quickstart_batchgetassetshistory.batch_get_assets_history(PROJECT, asset_names)
            out, _ = capsys.readouterr()
    
            assert bucket_asset_name in out
    
>       eventually_consistent_test()

quickstart_batchgetassetshistory_test.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.nox/py-3-8/lib/python3.8/site-packages/backoff/_sync.py:94: in retry
    ret = target(*args, **kwargs)
quickstart_batchgetassetshistory_test.py:57: in eventually_consistent_test
    quickstart_batchgetassetshistory.batch_get_assets_history(PROJECT, asset_names)
quickstart_batchgetassetshistory.py:33: in batch_get_assets_history
    response = client.batch_get_assets_history(
../../google/cloud/asset_v1/services/asset_service/client.py:391: in batch_get_assets_history
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
.nox/py-3-8/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py:145: in __call__
    return wrapped_func(*args, **kwargs)
.nox/py-3-8/lib/python3.8/site-packages/google/api_core/retry.py:281: in retry_wrapped_func
    return retry_target(
.nox/py-3-8/lib/python3.8/site-packages/google/api_core/retry.py:184: in retry_target
    return target()
.nox/py-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:59: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = None
from_value = <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "The following 1 reso...exist in projects/1012616486416 : //storage.googleapis.com/assets-2e67da2f1fed466d8d2352d28c811f2e","grpc_status":3}"
>

>   ???
E   google.api_core.exceptions.InvalidArgument: 400 The following 1 resources don't exist in projects/1012616486416 : //storage.googleapis.com/assets-2e67da2f1fed466d8d2352d28c811f2e

<string>:3: InvalidArgument</pre></details>

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #104
fixes #105

### CODE REVIEW

**Comment by tmatsuo** [comment]
@busunkim96 Also, can we make the sample tests required before merge?

**Comment by tmatsuo** [comment]
Oh, the test is still failing. I don't know why. I'll add the project id to `create_bucket` call explicitly too, and also try to bump the timeout.

**Comment by tmatsuo** [comment]
I'm completely baffled. Now it's constantly failing.

**Comment by tmatsuo** [comment]
This is blocked by a service issue. Internal reference: b/172361675

**Review by busunkim96 — APPROVED** [review]
Apologies for the late review, I didn't see this one in my inbox. 

Could you add make the samples session required via `.github/sync-repo-settings.yml`?  I'd like to make the samples checked required everywhere eventually, but doing that now will break repos without any samples.

The config is additive so I believe this will work:

```yml
branchProtectionRules:
 # List of required status check contexts that must pass for commits to be accepted to matching branches.
  requiredStatusCheckContexts:
    - 'Samples - Python 3.6'
    - 'Samples - Python 3.7'
    - 'Samples - Python 3.8'
    - 'Samples - Lint'
```
https://github.com/googleapis/python-bigtable/blob/ff3c57773ed34c41490f19871c4cc12ddc196cc0/.github/sync-repo-settings.yaml#L30-L32

**Comment by tmatsuo** [comment]
@busunkim96 Sure, I can add it with another PR.

**Pull request merged**
