### PR TITLE
chore: update CODEOWNERS

### PR DESCRIPTION
**Pull request by daniel-sanche**
Removing myself from CODEOWNERS file. This seems to be left over from when I was on the Infrastructure&Operations team

### CODE REVIEW

**Review by tmatsuo — COMMENTED** [review]
Can you leave @googleapis/python-samples-owners ?

**Comment by tmatsuo** [comment]
@busunkim96 I thought we added a config for repo-sync, but the sample tests are not required.

**Comment by Daniel-Sanche** [comment]
It looks like I'm not a member of python-sample-owners

**Comment by tmatsuo** [comment]
@Daniel-Sanche 

Ah sorry, what I meant is

You are deleting yourself and `googleapis/python-samples-owners` from the CODEOWNERS file.
Can you only delete yourself from the file?

**Comment by Daniel-Sanche** [comment]
Ah sorry I missed that! Should be fixed now

**Review by busunkim96 — APPROVED** [review]

**Review by busunkim96 — APPROVED** [review]

**Pull request merged**
